# Generated by Django 5.1.1 on 2024-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_jobmodel_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
